### PR TITLE
Add postgres 9.6 in travis for unit tests

### PR DESCRIPTION
**Pull request by syxolk**
See #37

### CODE REVIEW

**Comment by syxolk** [comment]
Sorry, why did you restore the branch?

**Comment by sebmarste** [comment]
We have reverted some pull requests as the tests did fail (because Travis did not find the DB ^^) and now we have to figure out how to put all the things together again, but we will handle that, thanks ;)

**Comment by syxolk** [comment]
I'm sorry that it didn't work as expected 😞

**Comment by sebmarste** [comment]
Haha happens, not a big problem ;)

**Pull request merged**
